### ISSUE TITLE
Graphite: Failed sending data

### ISSUE THREAD

**Issue by Azef1** [shinken-monitoring/mod-graphite#15]
Hi,
I have installed module graphite. 
I have configured in /etc/shinken/brokers/broker-master.cfg:  modules     webui2, graphite
I have modified in /etc/shinken/modules/graphite.cfg the port.
My graphite is on my localhost and on docker package. 
I use Grafana to visualize metrics.

The problem: Failed sendind data in log brokers:

[1446195036] ERROR: [broker-master] [Graphite broker] Failed sending data to the Graphite Carbon instance ! Trying to reconnect ...
[1446195036] INFO: [broker-master] [Graphite broker] I init the graphite server connection to localhost:5602
[1446195036] INFO: [broker-master] [Graphite broker] Connection successful to  localhost:5602
[1446195151] ERROR: [broker-master] [Graphite broker] Failed sending data to the Graphite Carbon instance ! Trying to reconnect ...
[1446195151] INFO: [broker-master] [Graphite broker] I init the graphite server connection to localhost:5602
[1446195151] INFO: [broker-master] [Graphite broker] Connection successful to  localhost:5602

Have you idea to fix it ?

Thx

**Comment by mohierf** [comment]
Are you sure that your metrics are not sent? Because the Graphite module logs an information if the metrics are lost because of connection failure ... currently the module tries to reconnect and succeeds and send the metrics because I do not see any logs with `metrics are lost`

I know ... quite strange logs for such a behaviour ... I just noticed this a few days ago in a testing environment :/P

**Comment by mohierf** [comment]
Any feedback about your problem?

Please remove the old version and install the new version `shinken install graphite2`. Same for the WebUI module ...

**Comment by Azef1** [comment]
Hi,
I re-installed shinken, webui2, graphite2, ui-graphite, mongo-logs and all options in default. 
Now, i haven't this problem !!
And i can see "Graphs" tabs because i forgot using in webui2.cfg: `modules ui-graphite`
But in my Grafana i doesn't see shinken's data.

I noticed errors in my broker log:)
`WARNING: The module type graphite-webui for ui-graphite was not found in modules!`
`ERROR: [WebUI] loading plugin availability, exception: No module named arrow`
`ERROR: [WebUI] loading plugin graphs, exception: No module named requests`

I think i forgot installed arrow and requests python module

**Comment by mohierf** [comment]
Yes ... you forgot them, see `requirements.txt` file ;-)

In `broker-master.cfg`, set `module graphite2` ...
In `webui2.cfg`, set `module ui-graphite2` ...

Do not forget to configure `graphite2.cfg` and `ui-graphite2.cfg` ... the files are self documented

**Comment by Azef1** [comment]
Ok i think the graphite module works because in my graphite folder i see some folders about my config (hosts, services) in  /var/lib/graphite/storage/whisper/
But the "ui-graphite" doesn't works because there aren't graphs
![errgraphs](https://cloud.githubusercontent.com/assets/15362041/10998978/9069425a-8499-11e5-8925-21189cd723db.PNG)

(mod graphite) Shinken->Graphite OK
(mod ui-graphite2) Graphite->Shinken NO

I am trying change port in ui-graphite2 but all my config is with default options.

**Comment by mohierf** [comment]
Did you configure your graphite server address in ui-graphite2.cfg ?

Do you have some error logs in the brokerd.log ? If so, you will find the URL that is used for the Graphite renderer ...

**Comment by Azef1** [comment]
My graphite is on the same server. 
In ui-graphite.cfg (no ui-graphite2.cfg i haven't this file with last release) i configured my server address.
The only error logs in brokerd.log is:
`The module type graphite-webui for ui-graphite was not found in modules!`

I checking my config....

**Comment by Azef1** [comment]
Now it's works !!!!!!!!!!!
Soluce: In ui-graphite.cfg `uri  http://@myserver:5602/graphite/`

**Comment by mohierf** [comment]
You should remove ui-graphite and install ui-graphite2 ... I fixed some bugs in ui-graphite and added new interesting features in this version.
