### ISSUE TITLE
Graphite module can't reconnect after carbon-cache restart

### ISSUE THREAD

**Issue by diogouchoas** [shinken-monitoring/mod-graphite#20]
Whenever I perform a carbon-cache daemon restart the graphite broker module stops working forever, even after the graphite ports being open again.

On the broker log I can see the following error message:

[1459954656] WARNING: [broker-master] [Graphite] Failed sending data to the Graphite Carbon instance ! Storing data in module cache ... 
[1459954656] WARNING: [broker-master] [Graphite] cached metrics 1 packets
[1459954656] INFO: [broker-master] [Graphite] 1 cached metrics packet(s) to send to Graphite
[1459954656] ERROR: [broker-master] [Graphite] exception: [Errno 32] Broken pipe
[1459954656] INFO: [broker-master] [Graphite] time to flush 0 cached metrics packet(s) (0.0002)

**Comment by mohierf** [comment]
Do you use the last version of the module: 2.1.3?

If so, I will propose a patch ... if you can apply it? Please add this code between lines 176 and 177:

```
            self.con = None
```

_PS:_ I do not have this error on my test configuration ...

**Comment by diogouchoas** [comment]
I'm using the latest version available for install with `shinken install graphite2`.
I'll try to include the line you suggested. 

Is this the change you're proposing I try?

```
except IOError:
            logger.warning("[Graphite] Failed sending data to the Graphite Carbon instance !"
                           " Storing data in module cache ... ")
            self.cache.append(packet)
            self.con = None
            logger.warning("[Graphite] cached metrics %d packets", len(self.cache))
            return False
```

**Comment by mohierf** [comment]
Yes, your change is ok.

The code in the Shinken module installed with `shinken install graphite2` is the source code that you will find in the _refactored_ branch ... not in the _master_ branch.

**Comment by diogouchoas** [comment]
That change solved the issue for me. Now the behavior is exactly as expected.
Thanks for the help.

**Comment by mohierf** [comment]
Thanks for the test and confirmation. I will push this fix in the repo soon.
