### ISSUE TITLE
Graphs are not shown in Shinken WebUI

### ISSUE THREAD

**Issue by hflocken** [shinken-monitoring/mod-graphite#29]
Hi,

I have installed Shinken with WebUI2 and Graphite2 in a docker container. Shinken is running on port 8080 which I have exposed to my host machine. On the Shinken WebUI I can see the menu entry External -> Graphite and in the service view and in the Services view there is a Graphs tab.

However, no information from Graphite is displayed:
- In the Graphs tab only broken links are displayed: 
![image](https://user-images.githubusercontent.com/43062232/52140552-66c77700-2653-11e9-9d18-01cdb13c2535.png)
- The broken images link to /graph?url=http%3A//localhost%3A8080/render/[...]. When I access that link in my browser, I'm redirected to the login page although I'm logged in
- when I select External -> Graphite a new tab opens with the dashboard

I would appreciate any hint that helps me fixing this issue. 

What I do not understand and what probably is the issue here is how Shinken is forwarding requests to external modules such as Graphite. I also tried to install PNP4, but there I get an HTTP 404 error when http://localhost:8080/pnp4nagios/ is called.

**Comment by maethor** [comment]
Hi @hflocken 

The link to  `/graph?url=http%3A//localhost%3A8080/render/[...]` should work, I don't understand why your are redirected to the login page. What is the exact version of the webui you are running?

This forwarding is kind of a proxy. It is done to avoid opening pnp4nagios to the global network, and having the webui authentification and authorization in front of pnp4nagios (or graphite).

I am not using graphite thow, so I don't think I will be able to help further.

**Comment by hflocken** [comment]
Hi @maethor,

I realized that I was missing of the prerequisites. I followed the instructions on this page and then it worked:
https://www.linode.com/docs/uptime/monitoring/how-to-install-graphite-and-grafana-on-ubuntu-14-04/
