### ISSUE TITLE
Module name conflicts with graphite-web module

### ISSUE THREAD

**Issue by hemebond** [shinken-monitoring/mod-graphite#8]
The graphite-web package, installed via apt, has a Python module named graphite. This ends up conflicting with this module, preventing it from being imported by the broker. I renamed it to "flint" in my local installation as a test and the Shinken module was then imported successfully.

**Comment by naparuba** [comment]
arg ok, I better understand your import fail so.

We will try to see how to fix this without breaking past installation
compatibility.

**Comment by hemebond** [comment]
Duplicate of #7. Apparently fixed in Shinken source.

**Comment by naparuba** [comment]
you means lastest master works? (the module order did change indeed).
